import {
  Destination,
  BlogPost,
  PricingPlan,
  Itinerary,
  Trip,
  Achievement,
} from './types';

export const popularDestinations: Destination[] = [
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    description:
      'A dazzling blend of ultramodern and traditional, Tokyo offers endless discoveries from neon-lit skyscrapers to serene temples.',
    bannerImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800',
    ],
    currency: 'JPY (¥)',
    language: 'Japanese',
    timezone: 'JST (UTC+9)',
    visaRequirements: 'Visa-free for many countries up to 90 days',
    safetyScore: 92,
    costOfLiving: '$$$',
    popularAttractions: [
      'Shibuya Crossing',
      'Senso-ji Temple',
      'Meiji Shrine',
      'Tsukiji Fish Market',
      'Akihabara',
    ],
    bestRestaurants: [
      'Sukiyabashi Jiro',
      'Ichiran Ramen',
      'Gonpachi Nishiazabu',
      'Narisawa',
    ],
    bestHotels: ['Park Hyatt Tokyo', 'Aman Tokyo', 'Hoshinoya Tokyo', 'Hotel Gracery Shinjuku'],
    transportation: 'World-class subway and rail system. Get a Suica or Pasmo card.',
    nightlife: 'Vibrant nightlife in Shibuya, Roppongi, and Shinjuku districts.',
    foodGuide:
      'From Michelin-starred restaurants to street food, Tokyo is a food paradise. Must-try: sushi, ramen, tempura, yakitori.',
    emergencyNumbers: [
      { service: 'Police', number: '110', description: 'Emergency police' },
      { service: 'Ambulance/Fire', number: '119', description: 'Medical and fire emergencies' },
    ],
    weather: 'Four distinct seasons. Spring (cherry blossoms) and autumn are most pleasant.',
    reviews: [],
    rating: 4.8,
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    description:
      'The City of Light captivates with its iconic landmarks, world-class museums, and romantic ambiance.',
    bannerImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
      'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=800',
      'https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=800',
    ],
    currency: 'EUR (€)',
    language: 'French',
    timezone: 'CET (UTC+1)',
    visaRequirements: 'Schengen visa for non-EU citizens',
    safetyScore: 78,
    costOfLiving: '$$$$',
    popularAttractions: [
      'Eiffel Tower',
      'Louvre Museum',
      'Notre-Dame Cathedral',
      'Sacré-Cœur',
      'Champs-Élysées',
    ],
    bestRestaurants: ["L'Ambroisie", 'Le Jules Verne', 'Septime', 'L\'As du Fallafel'],
    bestHotels: ['The Ritz Paris', 'Four Seasons George V', 'Le Bristol', 'Hotel Plaza Athénée'],
    transportation: 'Excellent Metro system, buses, and bike-sharing (Vélib\').',
    nightlife: 'Trendy bars in Le Marais, clubs near Bastille, cabarets in Montmartre.',
    foodGuide:
      'French cuisine at its finest. Must-try: croissants, escargots, coq au vin, crème brûlée.',
    emergencyNumbers: [
      { service: 'Police', number: '17', description: 'Emergency police' },
      { service: 'Ambulance', number: '15', description: 'Medical emergencies' },
      { service: 'Fire', number: '18', description: 'Fire emergencies' },
      { service: 'European Emergency', number: '112', description: 'All emergencies' },
    ],
    weather: 'Mild climate. Spring and fall are ideal. Summers can be warm.',
    reviews: [],
    rating: 4.7,
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    description:
      'An island paradise of lush rice terraces, ancient temples, and stunning beaches.',
    bannerImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1544644181-1484b3f4f62c?w=800',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
    ],
    currency: 'IDR (Rp)',
    language: 'Indonesian, Balinese',
    timezone: 'WITA (UTC+8)',
    visaRequirements: 'Visa on arrival for many countries (30 days)',
    safetyScore: 75,
    costOfLiving: '$',
    popularAttractions: [
      'Uluwatu Temple',
      'Tegallalang Rice Terraces',
      'Sacred Monkey Forest',
      'Tanah Lot',
      'Mount Batur',
    ],
    bestRestaurants: ['Locavore', 'Mozaic', 'Sarong', 'Warung Babi Guling Ibu Oka'],
    bestHotels: ['Four Seasons Bali', 'Mandapa Ritz-Carlton', 'Alila Ubud', 'Ayana Resort'],
    transportation: 'Scooter rental is popular. Grab and Gojek for rides.',
    nightlife: 'Beach clubs in Seminyak, bars in Canggu, cultural performances in Ubud.',
    foodGuide:
      'Rich flavors of Indonesian cuisine. Must-try: nasi goreng, babi guling, satay, gado-gado.',
    emergencyNumbers: [
      { service: 'Police', number: '110', description: 'Emergency police' },
      { service: 'Ambulance', number: '118', description: 'Medical emergencies' },
    ],
    weather: 'Tropical climate. Dry season (April-October) is best. Rainy season (November-March).',
    reviews: [],
    rating: 4.6,
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'USA',
    continent: 'North America',
    description:
      'The city that never sleeps, NYC buzzes with energy, culture, and endless possibilities.',
    bannerImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
      'https://images.unsplash.com/photo-1522083165195-3424ed23392f?w=800',
      'https://images.unsplash.com/photo-1500916434205-0c77489c6cf7?w=800',
    ],
    currency: 'USD ($)',
    language: 'English',
    timezone: 'EST (UTC-5)',
    visaRequirements: 'ESTA for visa waiver countries, visa required for others',
    safetyScore: 70,
    costOfLiving: '$$$$',
    popularAttractions: [
      'Statue of Liberty',
      'Central Park',
      'Times Square',
      'Empire State Building',
      'Brooklyn Bridge',
    ],
    bestRestaurants: ['Le Bernardin', "Peter Luger Steak House", "Katz's Delicatessen", 'Eleven Madison Park'],
    bestHotels: ['The Plaza', 'The Ritz-Carlton Central Park', 'The Standard High Line', '1 Hotel Brooklyn Bridge'],
    transportation: 'Extensive subway system, buses, taxis, and ride-sharing.',
    nightlife: 'World-famous nightlife from Broadway shows to rooftop bars and underground clubs.',
    foodGuide:
      'The ultimate food city. Must-try: NY pizza, bagels, cheesecake, street hot dogs.',
    emergencyNumbers: [
      { service: 'All Emergencies', number: '911', description: 'Police, Fire, Medical' },
    ],
    weather: 'Four distinct seasons. Hot summers, cold winters. Spring and fall are best.',
    reviews: [],
    rating: 4.7,
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
    description:
      'A Mediterranean gem blending Gaudí architecture, vibrant culture, and beautiful beaches.',
    bannerImage: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800',
      'https://images.unsplash.com/photo-1539037116277-4db20889f2b8?w=800',
      'https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?w=800',
    ],
    currency: 'EUR (€)',
    language: 'Spanish, Catalan',
    timezone: 'CET (UTC+1)',
    visaRequirements: 'Schengen visa for non-EU citizens',
    safetyScore: 72,
    costOfLiving: '$$$',
    popularAttractions: [
      'Sagrada Familia',
      'Park Güell',
      'La Rambla',
      'Gothic Quarter',
      'Camp Nou',
    ],
    bestRestaurants: ['Tickets', 'Disfrutar', "Cal Pep", 'Can Culleretes'],
    bestHotels: ['W Barcelona', 'Majestic Hotel', 'Hotel Arts', 'Cotton House Hotel'],
    transportation: 'Metro, buses, and trams. Walking and biking are great options.',
    nightlife: 'Legendary nightlife from beach clubs to Gothic Quarter bars.',
    foodGuide:
      'Catalan cuisine shines. Must-try: tapas, paella, jamón ibérico, crema catalana.',
    emergencyNumbers: [
      { service: 'All Emergencies', number: '112', description: 'Police, Fire, Medical' },
    ],
    weather: 'Mediterranean climate. Warm summers, mild winters. Best: April-June, Sept-Oct.',
    reviews: [],
    rating: 4.6,
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    continent: 'Asia',
    description:
      'A futuristic city of superlatives — tallest buildings, largest malls, and luxury beyond imagination.',
    bannerImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200',
    gallery: [
      'https://images.unsplash.com/photo-1549511431-8b5da4b355f2?w=800',
      'https://images.unsplash.com/photo-1472457897821-70d3819a0e24?w=800',
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
    ],
    currency: 'AED (د.إ)',
    language: 'Arabic, English',
    timezone: 'GST (UTC+4)',
    visaRequirements: 'Visa on arrival or e-visa for most countries',
    safetyScore: 95,
    costOfLiving: '$$$$',
    popularAttractions: [
      'Burj Khalifa',
      'Dubai Mall',
      'Palm Jumeirah',
      'Dubai Marina',
      'Desert Safari',
    ],
    bestRestaurants: ['Zuma', "Nobu", "Pierchic", "Al Hadheerah"],
    bestHotels: ['Burj Al Arab', 'Atlantis The Palm', 'Armani Hotel', 'Address Downtown'],
    transportation: 'Metro, taxis, and ride-hailing apps. Car rental is popular.',
    nightlife: 'Upscale clubs, rooftop bars, beach clubs, and desert parties.',
    foodGuide:
      'Global cuisine meets Middle Eastern flavors. Must-try: shawarma, hummus, kunafa, machboos.',
    emergencyNumbers: [
      { service: 'Police', number: '999', description: 'Emergency police' },
      { service: 'Ambulance', number: '998', description: 'Medical emergencies' },
      { service: 'Fire', number: '997', description: 'Fire emergencies' },
    ],
    weather: 'Desert climate. Hot year-round. Best: November-March for pleasant temperatures.',
    reviews: [],
    rating: 4.5,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'top-10-hidden-gems-europe',
    title: 'Top 10 Hidden Gems in Europe You Must Visit',
    excerpt:
      'Discover Europe\'s best-kept secrets from medieval villages to pristine beaches that most tourists never find.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800',
    category: 'Travel Tips',
    tags: ['Europe', 'Hidden Gems', 'Travel'],
    authorId: '1',
    authorName: 'Sarah Johnson',
    authorAvatar: 'https://i.pravatar.cc/150?img=47',
    likes: 234,
    comments: 45,
    bookmarks: 89,
    readTime: 8,
    publishedAt: '2025-07-10',
  },
  {
    id: '2',
    slug: 'budget-travel-southeast-asia',
    title: 'How to Travel Southeast Asia on $30 a Day',
    excerpt:
      'A complete guide to backpacking through Thailand, Vietnam, Cambodia, and more without breaking the bank.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800',
    category: 'Budget Travel',
    tags: ['Southeast Asia', 'Budget', 'Backpacking'],
    authorId: '2',
    authorName: 'Mike Chen',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    likes: 567,
    comments: 89,
    bookmarks: 234,
    readTime: 12,
    publishedAt: '2025-07-08',
  },
  {
    id: '3',
    slug: 'solo-travel-guide',
    title: 'The Ultimate Solo Travel Guide: Tips for First-Timers',
    excerpt:
      'Everything you need to know about traveling alone — safety tips, making friends, and finding yourself on the road.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800',
    category: 'Travel Tips',
    tags: ['Solo Travel', 'Safety', 'Tips'],
    authorId: '3',
    authorName: 'Emma Davis',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    likes: 432,
    comments: 67,
    bookmarks: 156,
    readTime: 10,
    publishedAt: '2025-07-05',
  },
  {
    id: '4',
    slug: 'foodie-guide-tokyo',
    title: 'A Foodie\'s Guide to Tokyo: 20 Must-Try Dishes',
    excerpt:
      'From Michelin-starred restaurants to hidden ramen shops, discover the best food Tokyo has to offer.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800',
    category: 'Food & Drink',
    tags: ['Tokyo', 'Food', 'Japan'],
    authorId: '1',
    authorName: 'Sarah Johnson',
    authorAvatar: 'https://i.pravatar.cc/150?img=47',
    likes: 321,
    comments: 54,
    bookmarks: 198,
    readTime: 15,
    publishedAt: '2025-07-01',
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    interval: 'month',
    features: [
      'Basic AI trip planner',
      '3 saved trips',
      'Basic itinerary generation',
      'Destination browsing',
      'Community access',
    ],
    highlighted: false,
    cta: 'Get Started',
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 9.99,
    interval: 'month',
    features: [
      'Unlimited AI trips',
      'Advanced itinerary with daily plans',
      'Priority AI processing',
      'Offline trip downloads',
      'PDF exports',
      'Interactive maps',
      'Packing lists & checklists',
      'Weather forecasts',
    ],
    highlighted: true,
    cta: 'Start Free Trial',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 19.99,
    interval: 'month',
    features: [
      'Everything in Premium',
      'Team trip planning',
      'Collaborative itineraries',
      'Custom AI preferences',
      'Expense tracking',
      'Calendar integration',
      'Unlimited exports',
      'Priority support',
      'API access',
    ],
    highlighted: false,
    cta: 'Go Pro',
  },
];

export const travelStyles = [
  { value: 'luxury', label: 'Luxury', icon: '👑' },
  { value: 'budget', label: 'Budget', icon: '💰' },
  { value: 'backpacking', label: 'Backpacking', icon: '🎒' },
  { value: 'adventure', label: 'Adventure', icon: '🏔️' },
  { value: 'family', label: 'Family', icon: '👨‍👩‍👧‍👦' },
  { value: 'business', label: 'Business', icon: '💼' },
  { value: 'romantic', label: 'Romantic', icon: '💕' },
  { value: 'solo', label: 'Solo', icon: '🧘' },
];

export const interestOptions = [
  { value: 'beach', label: 'Beach', icon: '🏖️' },
  { value: 'food', label: 'Food', icon: '🍽️' },
  { value: 'museums', label: 'Museums', icon: '🏛️' },
  { value: 'shopping', label: 'Shopping', icon: '🛍️' },
  { value: 'nature', label: 'Nature', icon: '🌿' },
  { value: 'hiking', label: 'Hiking', icon: '🥾' },
  { value: 'nightlife', label: 'Nightlife', icon: '🌃' },
  { value: 'photography', label: 'Photography', icon: '📸' },
  { value: 'culture', label: 'Culture', icon: '🎭' },
  { value: 'sports', label: 'Sports', icon: '⚽' },
];

export const achievements: Achievement[] = [
  { id: 'first_trip', name: 'First Trip!', description: 'Create your first trip plan', icon: '🎉' },
  { id: 'explorer', name: 'Explorer', description: 'Plan trips to 3 different continents', icon: '🌍' },
  { id: 'globetrotter', name: 'Globetrotter', description: 'Visit 10 countries', icon: '✈️' },
  { id: 'planner_pro', name: 'Planner Pro', description: 'Create 20 detailed itineraries', icon: '📋' },
  { id: 'social_butterfly', name: 'Social Butterfly', description: 'Get 100 likes on shared trips', icon: '🦋' },
  { id: 'foodie', name: 'Foodie', description: 'Save 50 restaurants', icon: '🍜' },
  { id: 'photographer', name: 'Photographer', description: 'Upload 30 travel photos', icon: '📷' },
  { id: 'budget_master', name: 'Budget Master', description: 'Plan 5 trips under $500', icon: '💎' },
];

export function generateItinerary(trip: Partial<Trip>): Itinerary {
  const dest = trip.destination || 'Unknown';
  const days = trip.startDate && trip.endDate
    ? Math.ceil((new Date(trip.endDate).getTime() - new Date(trip.startDate).getTime()) / (1000 * 60 * 60 * 24))
    : 5;

  const dailyPlan = Array.from({ length: days }, (_, i) => ({
    day: i + 1,
    date: new Date(new Date(trip.startDate || Date.now()).getTime() + i * 86400000).toISOString().split('T')[0],
    activities: [
      {
        time: '09:00',
        title: i === 0 ? 'Arrival & Check-in' : `Explore ${dest} - Day ${i + 1}`,
        description: i === 0
          ? 'Arrive at your destination, check into your hotel, and get settled.'
          : `Discover the best of ${dest} with guided tours and local experiences.`,
        location: `${dest} City Center`,
        lat: 35.6762 + i * 0.1,
        lng: 139.6503 + i * 0.1,
        duration: '3 hours',
        cost: 50 + i * 10,
        category: 'Sightseeing',
      },
      {
        time: '12:00',
        title: i === 0 ? 'Welcome Lunch' : 'Local Cuisine Experience',
        description: `Enjoy authentic local cuisine at one of ${dest}'s best restaurants.`,
        location: `${dest} Food District`,
        lat: 35.6862 + i * 0.1,
        lng: 139.6603 + i * 0.1,
        duration: '1.5 hours',
        cost: 30 + i * 5,
        category: 'Dining',
      },
      {
        time: '14:00',
        title: i % 2 === 0 ? 'Museum Visit' : 'Outdoor Adventure',
        description: i % 2 === 0
          ? 'Explore world-class museums and cultural exhibits.'
          : 'Hike scenic trails and discover natural wonders.',
        location: dest,
        lat: 35.6962 + i * 0.1,
        lng: 139.6703 + i * 0.1,
        duration: '2.5 hours',
        cost: 25 + i * 5,
        category: i % 2 === 0 ? 'Culture' : 'Adventure',
      },
    ],
    meals: [
      { type: 'breakfast' as const, restaurant: `Café ${dest}`, cuisine: 'International', estimatedCost: 15, address: `${dest} Main Street` },
      { type: 'lunch' as const, restaurant: `${dest} Kitchen`, cuisine: 'Local', estimatedCost: 25, address: `${dest} Food Street` },
      { type: 'dinner' as const, restaurant: `The ${dest} Grill`, cuisine: 'Fine Dining', estimatedCost: 50, address: `${dest} Downtown` },
    ],
    notes: `Day ${i + 1} of your ${dest} adventure. Don't forget your camera!`,
  }));

  return {
    summary: `An amazing ${days}-day journey through ${dest}, packed with culture, cuisine, and unforgettable experiences.`,
    dailyPlan,
    flights: [
      {
        airline: 'SkyWings Airlines',
        flightNumber: 'SW1234',
        departure: trip.departureCity || 'Your City',
        arrival: dest,
        departureTime: '08:00',
        arrivalTime: '14:00',
        price: 450,
        bookingUrl: '#',
      },
      {
        airline: 'SkyWings Airlines',
        flightNumber: 'SW5678',
        departure: dest,
        arrival: trip.departureCity || 'Your City',
        departureTime: '16:00',
        arrivalTime: '22:00',
        price: 420,
        bookingUrl: '#',
      },
    ],
    hotels: [
      {
        name: `Grand ${dest} Hotel`,
        rating: 4.5,
        pricePerNight: 150,
        address: `123 Main Street, ${dest}`,
        lat: 35.6762,
        lng: 139.6503,
        amenities: ['WiFi', 'Pool', 'Spa', 'Gym', 'Restaurant'],
        bookingUrl: '#',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
      },
      {
        name: `${dest} Boutique Inn`,
        rating: 4.2,
        pricePerNight: 95,
        address: `456 Oak Avenue, ${dest}`,
        lat: 35.6862,
        lng: 139.6603,
        amenities: ['WiFi', 'Breakfast', 'Rooftop Bar'],
        bookingUrl: '#',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
      },
    ],
    restaurants: [
      { name: `${dest} Bistro`, cuisine: 'Local', priceRange: '$$', rating: 4.5, address: `${dest} Food Street`, lat: 35.68, lng: 139.65, imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400' },
      { name: `Sky Garden Restaurant`, cuisine: 'International', priceRange: '$$$', rating: 4.7, address: `${dest} Heights`, lat: 35.69, lng: 139.66, imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400' },
      { name: `Street Food Market`, cuisine: 'Street Food', priceRange: '$', rating: 4.3, address: `${dest} Night Market`, lat: 35.67, lng: 139.64, imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400' },
    ],
    attractions: [
      { name: `${dest} Tower`, description: 'Iconic landmark with panoramic views.', category: 'Landmark', price: 20, duration: '2 hours', bestTimeToVisit: 'Morning', lat: 35.6762, lng: 139.6503, imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400', rating: 4.6 },
      { name: `${dest} National Museum`, description: 'World-class museum showcasing local history.', category: 'Museum', price: 15, duration: '3 hours', bestTimeToVisit: 'Afternoon', lat: 35.6862, lng: 139.6603, imageUrl: 'https://images.unsplash.com/photo-1566127444979-b3e2c7bfaedf?w=400', rating: 4.4 },
      { name: `${dest} Gardens`, description: 'Beautiful botanical gardens.', category: 'Nature', price: 10, duration: '2 hours', bestTimeToVisit: 'Morning', lat: 35.6962, lng: 139.6703, imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400', rating: 4.5 },
    ],
    hiddenGems: [
      { name: `Secret ${dest} Rooftop`, description: 'Hidden rooftop bar with amazing views.', type: 'Bar', lat: 35.70, lng: 139.68 },
      { name: `${dest} Vintage Market`, description: 'Underground vintage market with unique finds.', type: 'Shopping', lat: 35.71, lng: 139.69 },
    ],
    budget: {
      flights: 870,
      hotels: days * 150,
      food: days * 90,
      activities: days * 60,
      transportation: days * 30,
      shopping: 300,
      misc: 200,
      total: 870 + days * 150 + days * 90 + days * 60 + days * 30 + 300 + 200,
      currency: trip.currency || 'USD',
    },
    packingChecklist: [
      'Passport & travel documents',
      'Comfortable walking shoes',
      'Weather-appropriate clothing',
      'Universal power adapter',
      'Portable charger',
      'Sunscreen & sunglasses',
      'First aid kit',
      'Reusable water bottle',
      'Day backpack',
      'Travel insurance documents',
    ],
    safetyTips: [
      'Keep copies of important documents',
      'Use official transportation',
      'Be aware of common tourist scams',
      'Keep emergency numbers handy',
      'Share your itinerary with family',
    ],
    weatherForecast: Array.from({ length: days }, (_, i) => ({
      date: new Date(new Date(trip.startDate || Date.now()).getTime() + i * 86400000).toISOString().split('T')[0],
      condition: ['Sunny', 'Partly Cloudy', 'Sunny', 'Clear', 'Sunny'][i % 5],
      highTemp: 28 + (i % 3),
      lowTemp: 18 + (i % 2),
      humidity: 55 + i * 2,
      precipitation: i % 3 === 0 ? 10 : 0,
      icon: '☀️',
    })),
    localTransportation: [
      { type: 'Metro/Subway', description: 'Efficient subway system covering the city.', cost: '$2-5 per ride', tips: 'Get a multi-day pass for savings.' },
      { type: 'Bus', description: 'Extensive bus network.', cost: '$1-3 per ride', tips: 'Download local transit app.' },
      { type: 'Taxi/Ride-share', description: 'Available throughout the city.', cost: '$10-30 per trip', tips: 'Use ride-hailing apps for best prices.' },
    ],
    emergencyContacts: [
      { service: 'Police', number: '911', description: 'Emergency police services' },
      { service: 'Ambulance', number: '911', description: 'Medical emergencies' },
      { service: 'Tourist Police', number: '555-0123', description: 'Tourist-specific assistance' },
    ],
    travelAdvice: [
      'Learn a few basic phrases in the local language',
      'Try local street food for authentic experiences',
      'Visit popular attractions early to avoid crowds',
      'Keep some cash for small purchases',
      'Respect local customs and dress codes',
    ],
    photoSpots: [
      `${dest} Skyline Viewpoint`,
      `${dest} Old Town Square`,
      `${dest} Waterfront Promenade`,
      `${dest} Rooftop Observatory`,
    ],
    localFoods: [
      'Local specialty dish #1',
      'Traditional street food',
      'Regional dessert',
      'Popular local beverage',
    ],
    shoppingRecommendations: [
      'Local handicraft market',
      'Modern shopping mall',
      'Vintage and antique shops',
      'Duty-free shopping',
    ],
    alternativePlans: [
      'Visit museums and indoor attractions',
      'Enjoy spa and wellness activities',
      'Take a cooking class',
      'Explore shopping districts',
    ],
    timeline: [
      { time: 'Day 1', title: 'Arrival', description: 'Arrive and settle in', icon: '✈️' },
      { time: `Day ${days}`, title: 'Departure', description: 'Head home with amazing memories', icon: '🏠' },
    ],
  };
}
